# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-02 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_value', models.CharField(max_length=250)),
                ('sensor_position_x', models.CharField(max_length=250)),
                ('sensor_position_y', models.CharField(max_length=250)),
            ],
        ),
    ]
