# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-03 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_value1',
            field=models.CharField(default=76, max_length=250),
            preserve_default=False,
        ),
    ]
